---
- name: ensure dockerfile directories exist
  file:
    path: "{{ item }}"
    owner: "{{ ansible_ssh_user }}"
    state: directory
  with_items:
    - "{{ ansible_env.PWD }}/.ansible_cache"
    - "{{ ansible_env.PWD }}/.ansible_cache/docker"

- name: synchronize role to remote cache for Dockerfile build
  synchronize:
    src: ../
    dest: "{{ ansible_env.PWD }}/.ansible_cache/docker/neutron-network"
    archive: no
    checksum: yes
    recursive: yes

- name: ensure docker image configuration directory exists
  file:
    path: "{{ item }}"
    owner: "{{ ansible_ssh_user }}"
    state: directory
  with_items:
    - "{{ ansible_env.PWD }}/.ansible_cache/docker/neutron-network/playbooks/group_vars"

- name: update configuration used to build docker image from template
  template:
    src: ansible_cache/docker/neutron-network/playbooks/group_vars/all.yml
    owner: "{{ ansible_ssh_user }}"
    dest: "{{ ansible_env.PWD }}/.ansible_cache/docker/neutron-network/playbooks/group_vars/all.yml"

- name: ensure neutron docker image has been built
  docker_image:
    name: "{{ neutron_network_docker_username }}/{{ neutron_network_docker_imagename }}"
    path: "{{ ansible_env.PWD }}/.ansible_cache/docker/neutron-network"
    state: present

- name: ensure neutron data container exists
  docker:
    image: "{{ neutron_network_docker_username }}/{{ neutron_network_docker_imagename }}"
    name: "{{ neutron_network_docker_containername }}_data"
    command: >
      ansible-playbook 
        -i inventories/local.ini playbooks/offline_configuration.yml -e '{ 
          "neutron_log_verbose" : "{{ neutron_log_verbose }}",
          "neutron_log_debug" : "{{ neutron_log_debug }}",
          "neutron_log_dir" : "{{ neutron_log_dir }}",
          "neutron_rabbitmq_host" : "{{ neutron_rabbitmq_host|replace("127.0.0.1", ansible_docker0['ipv4']['address']) }}",
          "neutron_rabbitmq_port" : "{{ neutron_rabbitmq_port }}",
          "neutron_rabbitmq_neutron_password" :
            "{{ neutron_rabbitmq_neutron_password }}",
          "neutron_mysql_host" : "{{ neutron_mysql_host|replace("127.0.0.1", ansible_docker0['ipv4']['address']) }}",
          "neutron_mysql_port" : "{{ neutron_mysql_port }}",
          "neutron_mysql_neutron_password" :
            "{{ neutron_mysql_neutron_password }}",
          "neutron_compute_internal_url" : "{{ neutron_compute_internal_url|replace("127.0.0.1", ansible_docker0['ipv4']['address']) }}",
          "neutron_identity_host" : "{{ neutron_identity_host|replace("127.0.0.1", ansible_docker0['ipv4']['address']) }}",
          "neutron_identity_internal_url" : "{{ neutron_identity_internal_url|replace("127.0.0.1", ansible_docker0['ipv4']['address']) }}",
          "neutron_identity_admin_url" : "{{ neutron_identity_admin_url|replace("127.0.0.1", ansible_docker0['ipv4']['address']) }}",
          "neutron_identity_admin_token" : "{{ neutron_identity_admin_token }}",
          "neutron_identity_neutron_password" : "{{ neutron_identity_neutron_password }}" }'
    detach: no
    state: present

- name: wait until offline configuration is completed
  command: docker wait "{{ neutron_network_docker_containername }}_data"
  register: docker_wait
  changed_when: false

- name: collect offline configuration log
  command: docker logs "{{ neutron_network_docker_containername }}_data"
  register: offline_configuration_log
  changed_when: false

- name: display offline configuration log
  debug:
    msg: "{{ offline_configuration_log.stdout_lines }}"

- name: fail on offline configuration failure
  assert:
    that: docker_wait.stdout == "0"

- name: ensure neutron service is running
  docker:
    image: "{{ neutron_network_docker_username }}/{{ neutron_network_docker_imagename }}"
    name: "{{ neutron_network_docker_containername }}_server"
    volumes_from: "{{ neutron_network_docker_containername }}_data"
    ports:
      - 9696:9696
    privileged: yes
    detach: yes
    state: running

