---
- name: ensure sysctl is appropriately configured
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - { name: net.ipv4.ip_forward, value: 1 }
    - { name: net.ipv4.conf.all.rp_filter, value: 0 }
    - { name: net.ipv4.conf.default.rp_filter, value: 0 }

- name: ensure neutron network packages and dependencies are installed
  apt: 
    pkg: "{{ item }}"
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - neutron-dhcp-agent
    - neutron-l3-agent
    - neutron-metadata-agent
    - neutron-plugin-ml2
    - neutron-plugin-openvswitch-agent

- name: ensure neutron network is started and enabled
  service: 
    name: "{{ item }}"
    state: started 
    enabled: yes
  with_items:
    - neutron-plugin-openvswitch-agent
    - neutron-l3-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent
    - openvswitch-switch

- name: ensure that openvswitch integration bridge exists
  openvswitch_bridge:
    bridge: br-int
    state: present

- name: ensure that openvswitch external bridge exists
  openvswitch_bridge:
    bridge: br-ex
    state: present

- name: update script to configure openvswitch external bridge from template
  template:
    src: etc/network/if-up.d/configure_br-ex
    dest: /etc/network/if-up.d/configure_br-ex
    owner: root
    group: root
    mode: 0755
  register: update_network_configure_script

- name: ensure configure script is run at least once
  command: /etc/network/if-up.d/configure_br-ex
  when: update_network_configure_script|changed
