---
- name: ensure sysctl is appropriately configured
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - { name: net.ipv4.ip_forward, value: 1 }
    - { name: net.ipv4.conf.all.rp_filter, value: 0 }
    - { name: net.ipv4.conf.default.rp_filter, value: 0 }

- name: ensure neutron network packages and dependencies are installed
  apt: 
    pkg: "{{ item }}"
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - neutron-dhcp-agent
    - neutron-l3-agent
    - neutron-metadata-agent
    - neutron-plugin-ml2
    - neutron-plugin-openvswitch-agent
    - openvswitch-datapath-dkms

- name: ensure that neutron directories exist and have correct permissions
  file:
    path: "{{ item }}"
    owner: neutron
    group: neutron
    mode: 0700
    state: directory
  with_items:
    - /etc/neutron
    - /var/lib/neutron
    - /var/run/neutron
    - /var/lock/neutron
    - /var/log/neutron

- name: ensure supervisor is installed for dockerized deployments 
  apt: 
    pkg: "{{ item }}"
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - supervisor

- name: update supervisor configuration from template for dockerized deployments
  template:
    src: etc/supervisor/conf.d/supervisord.conf
    dest: /etc/supervisor/conf.d/supervisord.conf
    owner: root
    group: root
    mode: 0644

#    - dnsmasq
- name: ensure neutron network is started and enabled
  service: 
    name: "{{ item }}"
    state: started 
    enabled: yes
  with_items:
    - neutron-plugin-openvswitch-agent
    - neutron-l3-agent
    - neutron-dhcp-agent
    - neturon-metadata-agent
    - openvswitch-switch

- name: ensure that openvswitch integration bridge exists
  openvswitch_bridge:
    bridge: br-int
    state: present

- name: ensure that openvswitch external bridge exists
  openvswitch_bridge:
    bridge: br-ex
    state: present

- name: ensure that port connects external bridge to physical interface
  openvswitch_port:
    bridge: br-ex
    port: "{{ neutron_network_interface }}"
    state: present

#   - dnsmasq
- name: ensure neutron network is properly shut down for dockerized deployments
  service:
    name: "{{ item }}"
    state: stopped
    enabled: yes
  with_items:
    - neutron-plugin-openvswitch-agent
    - neutron-l3-agent
    - neutron-dhcp-agent
    - neturon-metadata-agent
    - openvswitch-switch
  when: neutron_network_dockerize_context is defined

