---
- name: wait for the neutron services to be ready
  wait_for:
    delay: 1
    host: "{{ openstack_network_endpoint_host }}"
    port: 9696

- name: ensure external network is registered
  neutron_network:
    auth_url: "{{ openstack_identity_internal_url }}"
    login_tenant_name: admin
    login_username: admin
    login_password: "{{ openstack_identity_admin_password }}"
    name: "{{ openstack_network_external_name }}"
    provider_network_type: gre
    provider_segmentation_id: 1
    router_external: true
    shared: true
    state: present

- name: ensure subnet for external network is registered
  neutron_subnet:
    auth_url: "{{ openstack_identity_internal_url }}"
    login_tenant_name: admin
    login_username: admin
    login_password: "{{ openstack_identity_admin_password }}"
    name: "{{ openstack_network_external_name }}-subnet"
    network_name: "{{ openstack_network_external_name }}"
    cidr: >
      {{ openstack_network_external_network }}
    enable_dhcp: false
    gateway_ip: "{{ openstack_network_external_ip }}"
    dns_nameservers: "{{ openstack_network_external_dns_servers }}"
    allocation_pool_start: >
      {{ openstack_network_external_allocation_pool_start }}
    allocation_pool_end: "{{ openstack_network_external_allocation_pool_end }}"
    state: present

