---
- name: ensure external network is registered
  neutron_network:
    auth_url: "{{ neutron_identity_internal_url }}"
    login_tenant_name: admin
    login_username: admin
    login_password: "{{ neutron_identity_admin_password }}"
    name: "{{ neutron_network_external_name }}"
    provider_network_type: gre
    router_external: true
    shared: true
    state: present

- name: ensure subnet for external network is registered
  neutron_subnet:
    auth_url: "{{ neutron_identity_internal_url }}"
    login_tenant_name: admin
    login_username: admin
    login_password: "{{ neutron_identity_admin_password }}"
    name: "{{ neutron_network_external_name }}-subnet"
    network_name: "{{ neutron_network_external_name }}"
    cidr: "{{ neutron_network_external_network }}"
    enable_dhcp: false
    gateway_ip: "{{ neutron_network_external_ip }}"
    dns_nameservers: "{{ neutron_network_external_dns_servers }}"
    allocation_pool_start: "{{ neutron_network_external_allocation_pool_start }}"
    allocation_pool_end: "{{ neutron_network_external_allocation_pool_end }}"
    state: present
